-- =========================================================
-- DiDe – PostgreSQL full installation script
-- =========================================================

-- 0) Required plugins
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1) Tables
-- 1.1) Users
CREATE TABLE IF NOT EXISTS public.users (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username             text,
  password_hash        text,
  role                 text,                       
  name                 text,
  surname              text,
  email                text,
  email_verified       boolean DEFAULT false,
  is_verified          boolean DEFAULT false,
  verify_token         text,
  verify_expires       timestamptz,
  is_active            boolean DEFAULT true,
  deleted_by           text,
  deleted_by_role      text,
  deleted_by_id        integer,
  deleted_at           timestamptz,
  reset_code           text,
  reset_expires        timestamptz,
  two_factor_enabled   boolean DEFAULT false,
  two_factor_secret    text,
  two_factor_norm_hash text
);

-- 1.2) event types
CREATE TABLE IF NOT EXISTS public.event_type (
  event_type_id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type_name          text,
  active                   boolean DEFAULT true,
  created_by_name          text,
  created_by_role_name     text,
  created_by_id            integer,
  created_at               timestamptz DEFAULT now(),
  "public_"                boolean,
  deactivated_by_name      text,
  deactivated_by_role_name text,
  deactivated_by_id        integer,
  deactivated_at           timestamptz,
  layer_table              text,
  attribute_column         text,
  is_point                 boolean DEFAULT true
);

-- 1.3) events (field records)
-- NOTE: Primary Key columns (from .env Primary_Keys) are dynamically added at runtime
CREATE TABLE IF NOT EXISTS public.event (
  event_id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  latitude                 double precision,
  longitude                double precision,
  event_type               integer REFERENCES public.event_type(event_type_id) ON UPDATE CASCADE ON DELETE SET NULL,
  description              text,
  geom                     geometry(Point,4326),
  created_by_name          text,
  created_by_role_name     text,
  created_by_id            integer,
  active                   boolean DEFAULT true,
  deactivated_by_name      text,
  deactivated_by_role_name text,
  deactivated_by_id        integer,
  deactivated_at           timestamptz,
  created_at               timestamptz DEFAULT now(),
  updated_by_name          text,
  updated_by_role_name     text,
  updated_by_id            integer,
  updated_at               timestamptz,
  photo_urls               text NOT NULL DEFAULT '[]',
  video_urls               text NOT NULL DEFAULT '[]'
);

-- 2) Indexes
CREATE INDEX IF NOT EXISTS users_username_idx ON public.users (lower(btrim(username)));
CREATE INDEX IF NOT EXISTS users_email_idx    ON public.users (lower(btrim(email)));
CREATE UNIQUE INDEX IF NOT EXISTS users_supervisor_totp_norm_uniq
  ON public.users (two_factor_norm_hash)
  WHERE role='supervisor' AND two_factor_norm_hash IS NOT NULL;

-- 3) Column defaults / type fixes (idempotent)
ALTER TABLE public.event  ALTER COLUMN photo_urls SET DEFAULT '[]';
ALTER TABLE public.event  ALTER COLUMN photo_urls SET NOT NULL;
ALTER TABLE public.event  ALTER COLUMN video_urls SET DEFAULT '[]';
ALTER TABLE public.event  ALTER COLUMN video_urls SET NOT NULL;