-- =========================================================
-- DiDe – PostgreSQL full installation script
-- =========================================================

-- 0) Required plugins
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1) Tables
-- 1.1) Users
CREATE TABLE IF NOT EXISTS public.users (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username             text,
  password_hash        text,
  role                 text,                       
  name                 text,
  surname              text,
  email                text,
  email_verified       boolean DEFAULT false,
  is_verified          boolean DEFAULT false,
  verify_token         text,
  verify_expires       timestamptz,
  is_active            boolean DEFAULT true,
  deleted_by           text,
  deleted_by_role      text,
  deleted_by_id        integer,
  deleted_at           timestamptz,
  reset_code           text,
  reset_expires        timestamptz,
  two_factor_enabled   boolean DEFAULT false,
  two_factor_secret    text,
  two_factor_norm_hash text,
  registration_date    timestamptz,
  solver               boolean DEFAULT false,
  num_events           integer DEFAULT 0,
  agreed_point         integer DEFAULT 0,
  posts_point          integer DEFAULT 0,
  current_point        integer DEFAULT 0      -- posts_point - spent points (orders); may be negative
);

-- 1.2) event types
CREATE TABLE IF NOT EXISTS public.event_type (
  event_type_id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type_name          text,
  active                   boolean DEFAULT true,
  created_by_name          text,
  created_by_role_name     text,
  created_by_id            integer,
  created_at               timestamptz DEFAULT now(),
  "public_"                boolean,
  deactivated_by_name      text,
  deactivated_by_role_name text,
  deactivated_by_id        integer,
  deactivated_at           timestamptz,
  layer_table              text,
  attribute_column         text,
  is_point                 boolean DEFAULT true,
  is_line                  boolean DEFAULT false,
  is_polygon               boolean DEFAULT false,
  time_dependent           boolean DEFAULT false,
  valid_time               double precision
);

-- 1.3) events (field records)
-- NOTE: Primary Key columns (from .env Primary_Keys) are dynamically added at runtime
CREATE TABLE IF NOT EXISTS public.event (
  event_id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  latitude                 double precision,
  longitude                double precision,
  event_type               integer REFERENCES public.event_type(event_type_id) ON UPDATE CASCADE ON DELETE SET NULL,
  description              text,
  geom                     geometry(Point,4326),
  created_by_name          text,
  created_by_role_name     text,
  created_by_id            integer,
  active                   boolean DEFAULT true,
  deactivated_by_name      text,
  deactivated_by_role_name text,
  deactivated_by_id        integer,
  deactivated_at           timestamptz,
  created_at               timestamptz DEFAULT now(),
  updated_by_name          text,
  updated_by_role_name     text,
  updated_by_id            integer,
  updated_at               timestamptz,
  photo_urls               text NOT NULL DEFAULT '[]',
  video_urls               text NOT NULL DEFAULT '[]',
  num_agrees               integer DEFAULT 0,      -- cached count of active rows in public.agrees
  last_agreed_date         timestamptz
);

-- 1.4) agrees (one row per agreement; replaces the old event.agreed_ids JSONB list)
--      agree_removed_date IS NULL  -> agreement is active
--      agree_removed_date NOT NULL -> user withdrew the agreement on that date
CREATE TABLE IF NOT EXISTS public.agrees (
  event_id                 integer NOT NULL REFERENCES public.event(event_id) ON UPDATE CASCADE ON DELETE CASCADE,
  agreed_user_id           integer NOT NULL,
  agree_date               timestamptz NOT NULL DEFAULT now(),
  agree_removed_date       timestamptz
);

-- 2) Indexes
CREATE INDEX IF NOT EXISTS users_username_idx ON public.users (lower(btrim(username)));
CREATE INDEX IF NOT EXISTS users_email_idx    ON public.users (lower(btrim(email)));
CREATE UNIQUE INDEX IF NOT EXISTS users_supervisor_totp_norm_uniq
  ON public.users (two_factor_norm_hash)
  WHERE role='supervisor' AND two_factor_norm_hash IS NOT NULL;
-- a user can have only ONE active agreement per event
CREATE UNIQUE INDEX IF NOT EXISTS agrees_event_user_active_uniq
  ON public.agrees (event_id, agreed_user_id) WHERE agree_removed_date IS NULL;
CREATE INDEX IF NOT EXISTS agrees_user_idx  ON public.agrees (agreed_user_id) WHERE agree_removed_date IS NULL;
CREATE INDEX IF NOT EXISTS agrees_event_idx ON public.agrees (event_id);

-- 3) Column defaults / type fixes (idempotent)
ALTER TABLE public.event  ALTER COLUMN photo_urls SET DEFAULT '[]';
ALTER TABLE public.event  ALTER COLUMN photo_urls SET NOT NULL;
ALTER TABLE public.event  ALTER COLUMN video_urls SET DEFAULT '[]';
ALTER TABLE public.event  ALTER COLUMN video_urls SET NOT NULL;

-- 4) Newer columns (idempotent)
-- 4.1) users
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS registration_date timestamptz;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS solver            boolean DEFAULT false;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS num_events        integer DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS agreed_point      integer DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS posts_point       integer DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS current_point     integer DEFAULT 0;

-- 4.2) event_type
ALTER TABLE public.event_type ADD COLUMN IF NOT EXISTS is_line        boolean DEFAULT false;
ALTER TABLE public.event_type ADD COLUMN IF NOT EXISTS is_polygon     boolean DEFAULT false;
ALTER TABLE public.event_type ADD COLUMN IF NOT EXISTS time_dependent boolean DEFAULT false;
ALTER TABLE public.event_type ADD COLUMN IF NOT EXISTS valid_time     double precision;

-- 4.3) event
ALTER TABLE public.event ADD COLUMN IF NOT EXISTS num_agrees       integer DEFAULT 0;
ALTER TABLE public.event ADD COLUMN IF NOT EXISTS last_agreed_date timestamptz;
